name: Convert SS Nodes

on:
  workflow_dispatch: 
  push:
    branch:
      - main
    paths:
      - "url.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run conversion script
      run: |
        python convert.py

    - name: Upload proxy configuration
      uses: actions/upload-artifact@v3
      with:
        name: config
        path: config.txt
      with:
        name: proxy-config
        path: proxy_config.txt
